# Generated by Django 5.0.4 on 2024-04-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("materia", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carrera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("duracion", models.IntegerField()),
                ("descripcion", models.TextField()),
                ("materia", models.ManyToManyField(to="materia.materia")),
            ],
        ),
    ]
