# Generated by Django 4.1.7 on 2024-03-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('nacimiento', models.DateField()),
                ('altura', models.IntegerField()),
            ],
        ),
    ]
