# Generated by Django 4.1.7 on 2024-03-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='ciudad',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
    ]
